export const NAMES_LIST = [
  "Outside Prosthetics restroom",
  "Outside Prosthetics restroom",
  "MSA front desk/office space (cubes)",
  "MSA office space/storage",
  "Restroom",
  "Restroom",
  "Backroom Prosthetic Storage",
  "small parallel bar room",
  "casting room",
  "clinic room",
  "clinic room",
  "Large parallel bar room",
  "WC Mainance",
  "Restroom",
  "Restroom",
  "Golf Simulator/Office space (cubes)",
  "Fitting Room",
  "Office Space (cubes)",
  "Dennis Office",
  "Plaster room",
  "Plastic Room",
  "Grinding Room",
  "Prosthetics Lab",
  "MAL",
  "MAL",
  "Kyle Office",
  "Sam Office",
  "John Office",
  "TBH Office",
  "Office Space (cubes)"
]
